export type ProductCategory = "All" | "Jeans" | "Shirts" | "Polo Shirts" | "Pants" | "Bags" | "T-Shirts";

export type Product = {
  id: string;
  name: string;
  category: ProductCategory;
  price: number;
  originalPrice?: number;
  image: string;
  description: string;
  sizes: string[];
  colors?: string[];
  fabric?: string;
  fit?: string;
  isNew?: boolean;
  isBestseller?: boolean;
  rating?: number;
  reviewsCount?: number;
};

export const STORE_INFO = {
  name: "MS PARK",
  tagline: "One and only unique brand in Chattogram",
  description:
    "MS Park is your premier destination for original ready-made garment collections. We craft and curate premium denim jeans, smart shirts, luxury polo shirts, luxury bags, and comfortable chinos.",
  address: "Shop no. 335, 3rd Floor, Yunusco City Centre, GEC Circle",
  city: "Chattogram, Bangladesh",
  phone: "+880 1614-354407",
  whatsapp: "+880 1614-354407",
  whatsappRaw: "8801614354407",
  facebookUrl: "https://www.facebook.com/msparkbd",
  facebookHandle: "@msparkbd",
  openingHours: "Saturday - Thursday: 10:00 AM - 10:00 PM | Friday: 3:00 PM - 10:00 PM",
  deliveryInfo: "Inside Chattogram: 1-2 Days (৳70) | All Over Bangladesh: 2-3 Days (৳130)",
};

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: "p-bag-1",
    name: "MS Park Signature Leather Travel Duffel",
    category: "Bags",
    price: 3450,
    originalPrice: 4200,
    image: "https://res.cloudinary.com/dwonhsf1i/image/upload/WhatsApp_Image_2026-08-25_at_3.39.39_PM.jpg",
    description: "Premium handcrafted leather duffel bag with heavy-duty brass hardware and spacious compartments.",
    sizes: ["One Size"],
    colors: ["Classic Brown", "Midnight Black"],
    fabric: "Genuine Leather Finish",
    isNew: true,
    isBestseller: true,
    rating: 5.0,
    reviewsCount: 24,
  },
  {
    id: "p-bag-2",
    name: "Urban Utility Crossbody Messenger Bag",
    category: "Bags",
    price: 2250,
    originalPrice: 2800,
    image: "https://res.cloudinary.com/dwonhsf1i/image/upload/WhatsApp_Image_2026-08-25_at_3.39.38_PM.jpg",
    description: "Sleek tactical messenger bag designed for urban commuters, featuring quick-access tech pockets.",
    sizes: ["One Size"],
    colors: ["Matte Black", "Olive Drab"],
    fabric: "Water-Resistant Canvas & Leather",
    isNew: true,
    isBestseller: true,
    rating: 4.9,
    reviewsCount: 18,
  },
  {
    id: "p-shirt-c1",
    name: "Premium Linen Patterned Casual Shirt",
    category: "Shirts",
    price: 2250,
    originalPrice: 2700,
    image: "https://res.cloudinary.com/dwonhsf1i/image/upload/WhatsApp_Image_2026-08-25_at_3.39.37_PM.jpg",
    description: "Breathable textured cotton linen shirt tailored for effortless smart casual style.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Custom Print"],
    fabric: "100% Breathable Linen Cotton",
    fit: "Modern Regular Fit",
    isNew: true,
    isBestseller: true,
    rating: 4.9,
    reviewsCount: 31,
  },
  {
    id: "p-shirt-c2",
    name: "Executive Stripe Oxford Cotton Shirt",
    category: "Shirts",
    price: 2150,
    originalPrice: 2550,
    image: "https://res.cloudinary.com/dwonhsf1i/image/upload/v1787769171/WhatsApp_Image_2026-08-25_at_3.39.36_PM_1.jpg",
    description: "Classic high-density woven stripe shirt for formal and business casual events.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Blue & White Stripe"],
    fabric: "100% Combed Cotton Oxford",
    fit: "Tailored Fit",
    isNew: true,
    isBestseller: true,
    rating: 4.8,
    reviewsCount: 27,
  },
  {
    id: "p-shirt-c3",
    name: "Minimalist Essential Crewneck T-Shirt",
    category: "T-Shirts",
    price: 1250,
    originalPrice: 1600,
    image: "https://res.cloudinary.com/dwonhsf1i/image/upload/v1787769168/WhatsApp_Image_2026-08-25_at_3.39.32_PM.jpg",
    description: "Heavyweight 220 GSM combed cotton t-shirt with soft-touch finishing and reinforced ribbed neckline.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Solid Navy", "Pure Black", "Heather Grey"],
    fabric: "100% Compact Organic Cotton",
    fit: "Streetwear Boxy Fit",
    isNew: true,
    isBestseller: false,
    rating: 4.7,
    reviewsCount: 15,
  },
  {
    id: "p-shirt-c4",
    name: "Monochrome Resort Collar Shirt",
    category: "Shirts",
    price: 2350,
    originalPrice: 2850,
    image: "https://res.cloudinary.com/dwonhsf1i/image/upload/v1787769172/WhatsApp_Image_2026-08-25_at_3.39.38_PM_1.jpg",
    description: "Contemporary Cuban collar shirt featuring lightweight drape fabric and relaxed holiday vibes.",
    sizes: ["M", "L", "XL"],
    colors: ["Black & White Pattern"],
    fabric: "Soft Rayon Linen Blend",
    fit: "Relaxed Fit",
    isNew: true,
    isBestseller: false,
    rating: 4.9,
    reviewsCount: 22,
  },
  {
    id: "p-shirt-c5",
    name: "Vintage Washed Oversized T-Shirt",
    category: "T-Shirts",
    price: 1350,
    originalPrice: 1750,
    image: "https://res.cloudinary.com/dwonhsf1i/image/upload/v1787769165/WhatsApp_Image_2026-08-25_at_3.39.21_PM.jpg",
    description: "Acid washed urban streetwear t-shirt crafted with premium heavy knit fabric.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Charcoal Wash"],
    fabric: "100% Cotton 240 GSM",
    fit: "Oversized Drop Shoulder",
    isNew: true,
    isBestseller: true,
    rating: 5.0,
    reviewsCount: 40,
  },
  {
    id: "p1",
    name: "Vintage Whisker Washed Slim Jeans",
    category: "Jeans",
    price: 2450,
    originalPrice: 2950,
    image: "https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=800&q=80",
    description: "Premium stretch denim with artisanal whisker wash and durable reinforced copper stitching.",
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Deep Indigo", "Vintage Blue"],
    fabric: "98% Cotton, 2% Elastane",
    fit: "Slim Fit",
    isNew: true,
    isBestseller: true,
    rating: 4.9,
    reviewsCount: 38,
  },
  {
    id: "p3",
    name: "Tailored Smart Casual Chino Pants",
    category: "Pants",
    price: 1950,
    originalPrice: 2350,
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=800&q=80",
    description: "Ultra-comfortable stretch twill chinos featuring a streamlined modern taper and stain-resistant finish.",
    sizes: ["30", "32", "34", "36"],
    colors: ["Khaki", "Olive Green", "Navy", "Charcoal"],
    fabric: "97% Cotton Twill, 3% Spandex",
    fit: "Tapered Fit",
    isNew: true,
    isBestseller: false,
    rating: 4.7,
    reviewsCount: 29,
  },
  {
    id: "p4",
    name: "Midnight Black Super Slim Denim",
    category: "Jeans",
    price: 2600,
    originalPrice: 3100,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80",
    description: "Deep reactive-dyed stay-black denim engineered to retain deep rich color through repeated washes.",
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Jet Black"],
    fabric: "98% Organic Cotton, 2% Lycra",
    fit: "Super Slim Fit",
    isNew: true,
    isBestseller: true,
    rating: 5.0,
    reviewsCount: 51,
  },
  {
    id: "p5",
    name: "Luxury Pique Structured Polo Shirt",
    category: "Polo Shirts",
    price: 1450,
    originalPrice: 1750,
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=800&q=80",
    description: "Double-mercerized Egyptian cotton polo shirt with contrast ribbed tipping collar and mother-of-pearl buttons.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Navy Blue", "Forest Green", "Burgundy"],
    fabric: "100% Mercerized Pique Cotton",
    fit: "Athletic Fit",
    isNew: true,
    isBestseller: true,
    rating: 4.9,
    reviewsCount: 64,
  },
];

export const CATEGORIES: { name: ProductCategory; count: number; image: string }[] = [
  {
    name: "Shirts",
    count: 24,
    image: "https://res.cloudinary.com/dwonhsf1i/image/upload/WhatsApp_Image_2026-08-25_at_3.39.37_PM.jpg",
  },
  {
    name: "Bags",
    count: 8,
    image: "https://res.cloudinary.com/dwonhsf1i/image/upload/WhatsApp_Image_2026-08-25_at_3.39.39_PM.jpg",
  },
  {
    name: "T-Shirts",
    count: 16,
    image: "https://res.cloudinary.com/dwonhsf1i/image/upload/v1787769165/WhatsApp_Image_2026-08-25_at_3.39.21_PM.jpg",
  },
  {
    name: "Jeans",
    count: 14,
    image: "https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Polo Shirts",
    count: 12,
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Pants",
    count: 10,
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=600&q=80",
  },
];

